//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GamesViewer_Xamarin.Resx {
    using System;
    using System.Reflection;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResources {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("GamesViewer_Xamarin.Resx.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string AppName {
            get {
                return ResourceManager.GetString("AppName", resourceCulture);
            }
        }
        
        internal static string ApiURL {
            get {
                return ResourceManager.GetString("ApiURL", resourceCulture);
            }
        }
        
        internal static string LoadingStr {
            get {
                return ResourceManager.GetString("LoadingStr", resourceCulture);
            }
        }
        
        internal static string LoadingTitle {
            get {
                return ResourceManager.GetString("LoadingTitle", resourceCulture);
            }
        }
        
        internal static string LoginStr {
            get {
                return ResourceManager.GetString("LoginStr", resourceCulture);
            }
        }
        
        internal static string RegisterStr {
            get {
                return ResourceManager.GetString("RegisterStr", resourceCulture);
            }
        }
        
        internal static string UsernameStr {
            get {
                return ResourceManager.GetString("UsernameStr", resourceCulture);
            }
        }
        
        internal static string PasswordStr {
            get {
                return ResourceManager.GetString("PasswordStr", resourceCulture);
            }
        }
        
        internal static string UsernameRegister {
            get {
                return ResourceManager.GetString("UsernameRegister", resourceCulture);
            }
        }
        
        internal static string EmailRegister {
            get {
                return ResourceManager.GetString("EmailRegister", resourceCulture);
            }
        }
        
        internal static string PasswordRegister {
            get {
                return ResourceManager.GetString("PasswordRegister", resourceCulture);
            }
        }
        
        internal static string RetypePasswordRegister {
            get {
                return ResourceManager.GetString("RetypePasswordRegister", resourceCulture);
            }
        }
        
        internal static string EnterUsername {
            get {
                return ResourceManager.GetString("EnterUsername", resourceCulture);
            }
        }
        
        internal static string EnterEmail {
            get {
                return ResourceManager.GetString("EnterEmail", resourceCulture);
            }
        }
        
        internal static string EnterPassword {
            get {
                return ResourceManager.GetString("EnterPassword", resourceCulture);
            }
        }
        
        internal static string EnterRetypePassword {
            get {
                return ResourceManager.GetString("EnterRetypePassword", resourceCulture);
            }
        }
        
        internal static string RegisterTitle {
            get {
                return ResourceManager.GetString("RegisterTitle", resourceCulture);
            }
        }
        
        internal static string EnumExistingUser {
            get {
                return ResourceManager.GetString("EnumExistingUser", resourceCulture);
            }
        }
        
        internal static string EnumExistingEmail {
            get {
                return ResourceManager.GetString("EnumExistingEmail", resourceCulture);
            }
        }
        
        internal static string EnumInvalidEmail {
            get {
                return ResourceManager.GetString("EnumInvalidEmail", resourceCulture);
            }
        }
        
        internal static string EnumUsernameNotFound {
            get {
                return ResourceManager.GetString("EnumUsernameNotFound", resourceCulture);
            }
        }
        
        internal static string EnumPasswordMismatch {
            get {
                return ResourceManager.GetString("EnumPasswordMismatch", resourceCulture);
            }
        }
        
        internal static string EnumOldNewPasswordSame {
            get {
                return ResourceManager.GetString("EnumOldNewPasswordSame", resourceCulture);
            }
        }
        
        internal static string EnumInternalError {
            get {
                return ResourceManager.GetString("EnumInternalError", resourceCulture);
            }
        }
        
        internal static string EnumOK {
            get {
                return ResourceManager.GetString("EnumOK", resourceCulture);
            }
        }
        
        internal static string RegisterOkMsg {
            get {
                return ResourceManager.GetString("RegisterOkMsg", resourceCulture);
            }
        }
        
        internal static string NoAutologinSupport {
            get {
                return ResourceManager.GetString("NoAutologinSupport", resourceCulture);
            }
        }
        
        internal static string PlatformsTitle {
            get {
                return ResourceManager.GetString("PlatformsTitle", resourceCulture);
            }
        }
        
        internal static string PlatformInfoTitle {
            get {
                return ResourceManager.GetString("PlatformInfoTitle", resourceCulture);
            }
        }
        
        internal static string NoDescription {
            get {
                return ResourceManager.GetString("NoDescription", resourceCulture);
            }
        }
        
        internal static string ViewPlatformGames {
            get {
                return ResourceManager.GetString("ViewPlatformGames", resourceCulture);
            }
        }
        
        internal static string PlatformGamesListTitle {
            get {
                return ResourceManager.GetString("PlatformGamesListTitle", resourceCulture);
            }
        }
        
        internal static string RefitError {
            get {
                return ResourceManager.GetString("RefitError", resourceCulture);
            }
        }
        
        internal static string GameInfoTitle {
            get {
                return ResourceManager.GetString("GameInfoTitle", resourceCulture);
            }
        }
        
        internal static string AvailableInfo {
            get {
                return ResourceManager.GetString("AvailableInfo", resourceCulture);
            }
        }
        
        internal static string RatingInfo {
            get {
                return ResourceManager.GetString("RatingInfo", resourceCulture);
            }
        }
        
        internal static string ReleaseDateInfo {
            get {
                return ResourceManager.GetString("ReleaseDateInfo", resourceCulture);
            }
        }
        
        internal static string DescriptionInfo {
            get {
                return ResourceManager.GetString("DescriptionInfo", resourceCulture);
            }
        }
        
        internal static string FavoritesTitle {
            get {
                return ResourceManager.GetString("FavoritesTitle", resourceCulture);
            }
        }
        
        internal static string SearchTitle {
            get {
                return ResourceManager.GetString("SearchTitle", resourceCulture);
            }
        }
        
        internal static string InputGame {
            get {
                return ResourceManager.GetString("InputGame", resourceCulture);
            }
        }
    }
}
